In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [16]:
a = np.array([1,3])
b = np.array([[1,-1],
             [6,4]
])

In [8]:
A = a*b
A

array([[ 1, -3],
       [ 6, 12]])

In [10]:
# eigen decomposition
eig_val, eig_vec = np.linalg.eig(A)

array([ 3., 10.])

In [12]:
# eigen value
eig_val

array([ 3., 10.])

In [13]:
# eigen vec
eig_vec

array([[-0.83205029,  0.31622777],
       [ 0.5547002 , -0.9486833 ]])