In [3]:
import numpy as np

# Soal 1

In [27]:
A1 = np.array([[23, 50],
               [7, 12]])

A2 = np.array([[57, 67],
               [99, 43]])

A3 = np.array([[75, 21],
               [57, 12]])

A4 = np.array([[87, 26],
               [18, 84]])

In [29]:
tensor = np.array([A1, A2, A3, A4])
tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

# Soal 2

In [18]:
A = np.array([[23,50,19],
              [7,12,109],
              [57,67,98]

])

B = np.array([17,22,19])

In [19]:
A @ B

array([1852, 2454, 4305])

# Soal 3

In [21]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [22]:
# Transpose

A.transpose()

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [23]:
# Mencari Determinant

np.linalg.det(A)

131344.0000000002

In [25]:
# Inverse dari matrix A

np.linalg.inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])